spring:
  datasource:
    url: jdbc:h2:mem:week5-testdb;MODE=MySQL;
  jpa:
    hibernate:
      ddl-auto: create

test:
  id-info:
    exist-id: 1
    not-exist-id: 1000
  create-info:
    name: My Name
    email: my@gmail.com
    invalid-email: gmail.com
    password: My Password
  update-info:
    name: Your Name
    password: Your Password
